name = "Jessica's Theme"
license = "MIT"
description = "Jessica's Practice Theme"
tags = []
features = []
min_version = "0.25.1"

[author]
  name = "Jessica Cranford"
  homepage = "https://jessicacranford.com/"
